### ISSUE TITLE
Infografía JavaScript 

### ISSUE THREAD

**Issue by ToniDepp** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-ToniDepp#1]
[JS-EDUARDO-TOMAS-IS-6US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-ToniDepp/files/15204632/JS-EDUARDO-TOMAS-IS-6US.pdf)

**Comment by Luz1727** [comment]
buen trabajo solo que le falto un poco mas de informacion 
18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
